import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'C++ 算法笔记',
  description: '纸质笔记数字化网站',
  themeConfig: {
    nav: [
      { text: '首页', link: '/' },
      { text: 'Page 1', link: '/page-1.html' },
      { text: 'Page 2', link: '/page-2.html' },
      { text: 'Page 3', link: '/page-3.html' },
      { text: 'Page 4', link: '/page-4.html' },
      { text: 'Page 5', link: '/page-5.html' },
      { text: 'Page 6', link: '/page-6.html' },
      { text: 'Page 7', link: '/page-7.html' },
      { text: 'Page 8', link: '/page-8.html' },
      { text: 'Page 9', link: '/page-9.html' },
      { text: 'Page 10', link: '/page-10.html' },
      { text: 'Page 11', link: '/page-11.html' },
      { text: 'Page 12', link: '/page-12.html' },
      { text: 'Page 13', link: '/page-13.html' },
      { text: 'Page 14', link: '/page-14.html' },
      { text: 'Page 15', link: '/page-15.html' },
      { text: 'Page 16', link: '/page-16.html' },
      { text: 'Page 17', link: '/page-17.html' },
      { text: 'Page 18', link: '/page-18.html' },
      { text: 'Page 19', link: '/page-19.html' },
      { text: 'Page 20', link: '/page-20.html' },
      { text: 'Page 21', link: '/page-21.html' },
      { text: 'Page 22', link: '/page-22.html' },
      { text: 'Page 23', link: '/page-23.html' },
      { text: 'Page 23-1', link: '/page-23-1.html' },
      { text: 'Page 23-2', link: '/page-23-2.html' },
      { text: 'Page 23-3', link: '/page-23-3.html' },
      { text: 'Page 24', link: '/page-24.html' },
      { text: 'Page 25', link: '/page-25.html' },
      { text: 'Page 26', link: '/page-26.html' },
      { text: 'Page 27', link: '/page-27.html' },
      { text: 'Page 28', link: '/page-28.html' },
      { text: 'Page 29', link: '/page-29.html' },
      { text: 'Page 30', link: '/page-30.html' },
      { text: 'Page 31', link: '/page-31.html' },
      { text: 'Page 32', link: '/page-32.html' },
      { text: 'Page 33', link: '/page-33.html' },
      { text: 'Page 34', link: '/page-34.html' },
      { text: 'Page 35', link: '/page-35.html' },
      { text: 'Page 36', link: '/page-36.html' },
      { text: 'Page 37', link: '/page-37.html' },
      { text: 'Page 38', link: '/page-38.html' },
      { text: 'Page 39', link: '/page-39.html' },
    ],
    sidebar: [
      { text: '首页', link: '/' },
      { text: 'Page 1', link: '/page-1.html' },
      { text: 'Page 2', link: '/page-2.html' },
      { text: 'Page 3', link: '/page-3.html' },
      { text: 'Page 4', link: '/page-4.html' },
      { text: 'Page 5', link: '/page-5.html' },
      { text: 'Page 6', link: '/page-6.html' },
      { text: 'Page 7', link: '/page-7.html' },
      { text: 'Page 8', link: '/page-8.html' },
      { text: 'Page 9', link: '/page-9.html' },
      { text: 'Page 10', link: '/page-10.html' },
      { text: 'Page 11', link: '/page-11.html' },
      { text: 'Page 12', link: '/page-12.html' },
      { text: 'Page 13', link: '/page-13.html' },
      { text: 'Page 14', link: '/page-14.html' },
      { text: 'Page 15', link: '/page-15.html' },
      { text: 'Page 16', link: '/page-16.html' },
      { text: 'Page 17', link: '/page-17.html' },
      { text: 'Page 18', link: '/page-18.html' },
      { text: 'Page 19', link: '/page-19.html' },
      { text: 'Page 20', link: '/page-20.html' },
      { text: 'Page 21', link: '/page-21.html' },
      { text: 'Page 22', link: '/page-22.html' },
      { text: 'Page 23', link: '/page-23.html' },
      { text: 'Page 23-1', link: '/page-23-1.html' },
      { text: 'Page 23-2', link: '/page-23-2.html' },
      { text: 'Page 23-3', link: '/page-23-3.html' },
      { text: 'Page 24', link: '/page-24.html' },
      { text: 'Page 25', link: '/page-25.html' },
      { text: 'Page 26', link: '/page-26.html' },
      { text: 'Page 27', link: '/page-27.html' },
      { text: 'Page 28', link: '/page-28.html' },
      { text: 'Page 29', link: '/page-29.html' },
      { text: 'Page 30', link: '/page-30.html' },
      { text: 'Page 31', link: '/page-31.html' },
      { text: 'Page 32', link: '/page-32.html' },
      { text: 'Page 33', link: '/page-33.html' },
      { text: 'Page 34', link: '/page-34.html' },
      { text: 'Page 35', link: '/page-35.html' },
      { text: 'Page 36', link: '/page-36.html' },
      { text: 'Page 37', link: '/page-37.html' },
      { text: 'Page 38', link: '/page-38.html' },
      { text: 'Page 39', link: '/page-39.html' },
    ]
  }
})
