import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'C++ 算法笔记',
  description: '纸质笔记数字化网站',
  themeConfig: {
    nav: [
      { text: '首页', link: '/' },
      { text: '索引', link: '/page-1' },
      { text: 'Page 2', link: '/page-2' },
      { text: 'Page 3', link: '/page-3' },
      { text: 'Page 4', link: '/page-4' },
      { text: 'Page 5', link: '/page-5' },
      { text: 'Page 6', link: '/page-6' },
      { text: 'Page 7', link: '/page-7' },
      { text: 'Page 8', link: '/page-8' },
      { text: 'Page 9', link: '/page-9' },
      { text: 'Page 10', link: '/page-10' },
      { text: 'Page 11', link: '/page-11' },
      { text: 'Page 12', link: '/page-12' },
      { text: 'Page 13', link: '/page-13' },
      { text: 'Page 14', link: '/page-14' },
      { text: 'Page 15', link: '/page-15' },
      { text: 'Page 16', link: '/page-16' },
      { text: 'Page 17', link: '/page-17' },
      { text: 'Page 18', link: '/page-18' },
      { text: 'Page 19', link: '/page-19' },
      { text: 'Page 20', link: '/page-20' },
      { text: 'Page 21', link: '/page-21' },
      { text: 'Page 22', link: '/page-22' },
      { text: 'Page 23', link: '/page-23' },
      { text: 'Page 24', link: '/page-24' },
      { text: 'Page 25', link: '/page-25' },
      { text: 'Page 26', link: '/page-26' },
      { text: 'Page 27', link: '/page-27' },
      { text: 'Page 28', link: '/page-28' },
      { text: 'Page 29', link: '/page-29' },
      { text: 'Page 30', link: '/page-30' },
      { text: 'Page 31', link: '/page-31' },
      { text: 'Page 32', link: '/page-32' },
      { text: 'Page 33', link: '/page-33' },
    ],
    sidebar: [
      { text: '首页', link: '/' },
      { text: '索引', link: '/page-1' },
      { text: 'Page 2', link: '/page-2' },
      { text: 'Page 3', link: '/page-3' },
      { text: 'Page 4', link: '/page-4' },
      { text: 'Page 5', link: '/page-5' },
      { text: 'Page 6', link: '/page-6' },
      { text: 'Page 7', link: '/page-7' },
      { text: 'Page 8', link: '/page-8' },
      { text: 'Page 9', link: '/page-9' },
      { text: 'Page 10', link: '/page-10' },
      { text: 'Page 11', link: '/page-11' },
      { text: 'Page 12', link: '/page-12' },
      { text: 'Page 13', link: '/page-13' },
      { text: 'Page 14', link: '/page-14' },
      { text: 'Page 15', link: '/page-15' },
      { text: 'Page 16', link: '/page-16' },
      { text: 'Page 17', link: '/page-17' },
      { text: 'Page 18', link: '/page-18' },
      { text: 'Page 19', link: '/page-19' },
      { text: 'Page 20', link: '/page-20' },
      { text: 'Page 21', link: '/page-21' },
      { text: 'Page 22', link: '/page-22' },
      { text: 'Page 23', link: '/page-23' },
      { text: 'Page 24', link: '/page-24' },
      { text: 'Page 25', link: '/page-25' },
      { text: 'Page 26', link: '/page-26' },
      { text: 'Page 27', link: '/page-27' },
      { text: 'Page 28', link: '/page-28' },
      { text: 'Page 29', link: '/page-29' },
      { text: 'Page 30', link: '/page-30' },
      { text: 'Page 31', link: '/page-31' },
      { text: 'Page 32', link: '/page-32' },
      { text: 'Page 33', link: '/page-33' },
    ]
  }
})